name: predict-customer-churn
channels:
  - conda-forge
  - defaults
dependencies:
  - astroid=3.1.0
  - autopep8=2.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - cfgv=3.3.1
  - colorama=0.4.6
  - contourpy=1.2.1
  - cycler=0.12.1
  - dill=0.3.8
  - distlib=0.3.8
  - exceptiongroup=1.2.0
  - filelock=3.13.4
  - fonttools=4.51.0
  - freetype=2.12.1
  - identify=2.5.35
  - iniconfig=2.0.0
  - isort=5.13.2
  - joblib=1.4.0
  - kiwisolver=1.4.5
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsqlite=3.45.2
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=18.1.3
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - mccabe=0.7.0
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - nodeenv=1.8.0
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.2.1
  - packaging=24.0
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - platformdirs=4.2.0
  - plotly=5.19.0
  - pluggy=1.4.0
  - pre-commit=3.7.0
  - pthread-stubs=0.4
  - pycodestyle=2.11.1
  - pycparser=2.22
  - pylint=3.1.0
  - pyparsing=3.1.2
  - pytest=8.1.1
  - python=3.12.2
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - readline=8.2
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - setuptools=69.5.1
  - six=1.16.0
  - tenacity=8.2.3
  - threadpoolctl=3.4.0
  - tk=8.6.13
  - tomli=2.0.1
  - tomlkit=0.12.4
  - tornado=6.4
  - typing_extensions=4.11.0
  - tzdata=2024a
  - ukkonen=1.0.1
  - virtualenv=20.25.1
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zstd=1.5.5
